import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    justifyContent: 'space-between',
    backgroundColor: '#BA4849',
    elevation: 3,
  },
  headerTitle: {
    fontSize: 20,
    color: '#ffff',
    fontWeight: '600',
    marginLeft: 10,
  },
  PomodoroView: {
    marginHorizontal: 10,
    marginTop: 10,
    // height: '50%',
    borderRadius: 8,
    backgroundColor: '#C25C5C',
    alignItems: 'center',
    paddingVertical: 24,
  },
  PomodoroText: {
    fontSize: 20,
    fontWeight: '600',
    color: '#fff',
    textAlign: 'center',
  },
  counterText: {
    textAlign: 'center',
    fontSize: 65,
    fontWeight: '600',
    color: '#fff',
    paddingTop: 10,
  },
  startBtn: {
    padding: 10,
    width: '40%',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#fff',
    borderRadius: 6,
    marginTop: 10,
  },
  satrtText: {
    fontSize: 18,
    color: '#C25C5C',
    fontWeight: '800',
  },
  countText: {
    color: '#000',
    fontSize: 16,
    fontWeight: '600',
  },
  addBtn: {
    // width: 50,
    padding: 18,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'gray',
    position: 'absolute',
    bottom: 10,
    right: 10,
    paddingHorizontal: 25,
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  sheet: {
    padding: 15,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    backgroundColor: '#EFEFEF',
  },
  handleBar: {
    width: 50,
    height: 5,
    backgroundColor: '#ccc',
    borderRadius: 3,
    alignSelf: 'center',
    marginVertical: 10,
  },
  contentText: {
    textAlign: 'center',
    marginVertical: 20,
    fontSize: 16,
  },
  addTaskField: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    color: '#000',
    margin: 5,
    borderColor: '#ccc',
  },
  addTaskText: {
    fontSize: 16,
    fontWeight: '500',
    paddingVertical: 5,
  },
  upDownBtn: {
    borderWidth: 1,
    padding: 10,
    borderRadius: 6,
    marginHorizontal: 8,
  },
  cancelBtn: {
    // borderWidth: 1,
    padding: 10,
    margin: 10,
    width: '30%',
    borderRadius: 8,
    alignItems: 'center',
    backgroundColor: '#ad4142',
  },
  cancelText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#fff',
  },
  estValue: {
    // borderWidth: 1,
    width: '18%',
    alignItems: 'center',
    borderColor: '#ccc',
    borderRadius: 8,
    // marginHorizontal: 5,
    // paddingHorizontal: 10,
    color: '#000',
    justifyContent: 'center',
    backgroundColor: '#ccc',
  },
  allTaskView: {
    backgroundColor: '#fff',
    padding: 6,
    borderRadius: 6,
    elevation: 3,
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  viewAllstyle: {
    flexDirection: 'row',
    width: '98%',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    marginTop: 10,
    borderColor: 'gray',
  },
  timerText: {fontSize: 16, fontWeight: '800', color: 'gray'},
  settingStyle: {
    textAlign: 'center',
    marginTop: 10,
    borderBottomWidth: 0.9,
    borderColor: '#ccc',
    paddingVertical: 6,
    fontSize: 18,
    fontWeight: '800',
    color: 'gray',
  },
  settingPomodoro: {
    width: '40%',
    borderRadius: 8,
    flexDirection: 'row',
    backgroundColor: '#ccc',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 6,
    marginTop: 8,
  },
  rowCenter: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    justifyContent: 'space-between',
  },
  settingView: {
    backgroundColor: '#fff',
    width: '100%',
    alignSelf: 'center',
    // height: '80%',
    marginTop: 40,
    borderRadius: 8,
    elevation: 5,
    // flex:1
  },
  divaider: {
    width: '95%',
    height: 1,
    backgroundColor: '#ccc',
    alignSelf: 'center',
  },
  dropdown: {
    height: 40,
    borderColor: 'gray',
    borderWidth: 0.5,
    borderRadius: 6,
    paddingHorizontal: 8,
    width: '40%',
    backgroundColor: '#EBEBEB',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  placeholderStyle: {
    fontSize: 14,
  },
  selectedTextStyle: {
    fontSize: 16,
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  saveBtn: {
    width: '30%',
    backgroundColor: '#373737',
    alignItems: 'center',
    padding: 10,
    alignSelf: 'center',
    marginBottom: 50,
    borderRadius: 4,
  },
  runningText: {
    position: 'absolute',
    top: 0,
    right: 10,
    fontSize: 10,
    fontWeight: '500',
    color: 'green',
  },
  alarmText: {
    color: '#000',
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
    paddingVertical: 8,
  },
  alarmListView: {
    borderWidth: 1,
    margin: 3,
    padding: 6,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 3,
    borderColor: 'gray',
  },
  soundName: {
    color: '#000',
    fontSize: 16,
    fontWeight: '600',
    width: '70%',
  },
  alarmListOkBtn: {
    width: '16%',
    position: 'absolute',
    right: 10,
    top: 5,
    backgroundColor: '#333333',
    paddingVertical: 4,
    borderRadius: 5,
  },
  alarmListOkBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  dropdownTime: {
    height: 40,
    borderColor: 'gray',
    borderWidth: 0.5,
    borderRadius: 8,
    paddingHorizontal: 5,
    width: '40%',
  },
  theamView: {
    backgroundColor: '#38848A',
    width: 30,
    height: 30,
    borderRadius: 4,
    margin: 2,
  },
  dateTaskText: {
    fontSize: 16,
    fontWeight: '600',width:'20%',fontStyle:'italic'
  },
});

export default styles;
